version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mern_library_nginx_mongodb_1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    container_name: mern_library_nginx_mongo-express_1
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb

  server:
    build: ./server
    container_name: library_mern_nginx
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017
      NODE_ENV: development
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb

  client:
    build: ./client
    container_name: library_mern_frontend
    ports:
      - "3000:3000"
    environment:
      DISABLE_ESLINT_PLUGIN: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client:/app
      - /app/node_modules

  nginx:
    build: ./nginx
    container_name: mern_library_nginx_nginx_1
    ports:
      - "8080:80"
    depends_on:
      - server
      - client
